apiVersion: v1
kind: PersistentVolume
metadata:
  name: tautulli-data
spec:
  storageClassName: tautulli-data
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: tautulli-data
    volumeAttributes:
      dataLocality: best-effort
      numberOfReplicas: "1"
      staleReplicaTimeout: "30"
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: "5Gi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tautulli-claim
spec:
  storageClassName: tautulli-data
  volumeName: tautulli-data
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "5Gi"

