apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hubble
  namespace: kube-system
spec:
  secretName: hubble-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - hubble.staging.cruznet.io

