apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: hubble
  namespace: kube-system
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`hubble.cruznet.io`)
    kind: Rule
    services:
    - name: hubble-ui
      kind: Service
      namespace: kube-system
      port: 80
  tls:
    secretName: hubble-cert

