apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: traefik-pool
spec:
  blocks:
  - start: "172.31.1.248"
  serviceSelector:
    matchLabels:
      "io.kubernetes.service.name": "traefik"

