apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homepage-staging
resources:
  - ../../base/homepage

patches:
- target:
    kind: IngressRoute
    name: homepage
  patch: |-
    - op: replace
      path: /spec/routes/0/match
      value: Host(`homepage.staging.cruznet.io`)
- target:
    kind: Certificate
    name: homepage
  patch: |-
    - op: replace
      path: /spec/dnsNames/0
      value: homepage.staging.cruznet.io

