apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik
  namespace: traefik
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`traefik-new.cruznet.io`)
    kind: Rule
    services:
    - name: traefik
      kind: Service
      namespace: traefik
      port: 8080
  tls:
    secretName: traefik-cert

