apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
  namespace: traefik
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`traefik.cruznet.io`)
    kind: Rule
    services:
    - name: api@internal
      kind: TraefikService
      namespace: traefik
  tls:
    secretName: traefik-cert

