apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: it-tools
  namespace: it-tools
spec:
  secretName: it-tools-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - it-tools.cruznet.io

