apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  - ../../base/traefik

patches:
- target:
    kind: CiliumLoadBalancerIPPool
    name: traefik-pool
  patch: |-
    - op: replace
      path: /spec/blocks/0/start
      value: "172.31.1.248"

