apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: plex
  namespace: plex
spec:
  secretName: plex-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - plex-new.cruznet.io
  - plex.cruznet.io

