apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: plex
spec:
  interval: 30m
  chart:
    spec:
      chart: plex
      version: 6.4.x
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: plex
      interval: 12h
  valuesFrom:
  - kind: ConfigMap
    name: plex-values

