apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: plex-service-account
  namespace: plex
  labels:
    app.kubernetes.io/name: plex
  annotations:
    kubernetes.io/service-account.name: plex

