apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: prowlarr-service-account
  namespace: prowlarr
  labels:
    app.kubernetes.io/name: prowlarr
  annotations:
    kubernetes.io/service-account.name: prowlarr

