apiVersion: v1
kind: PersistentVolume
metadata:
  name: prowlarr-data
spec:
  storageClassName: prowlarr-data
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: prowlarr-data
    volumeAttributes:
      dataLocality: best-effort
      numberOfReplicas: "1"
      staleReplicaTimeout: "30"
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: "5Gi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-claim
  labels:
    recurring-job.longhorn.io/source: "enabled"
    recurring-job.longhorn.io/backup-daily-with-weekly-full: "enabled"
spec:
  storageClassName: prowlarr-data
  volumeName: prowlarr-data
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "5Gi"

