apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana
  namespace: prometheus-stack
spec:
  secretName: grafana-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - grafana.staging.cruznet.io

