apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-smb-media
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - vers=2.0
  csi:
    driver: smb2.csi.k8s.io
    readOnly: false
    volumeHandle: nas.cruznet.io##Media
    volumeAttributes:
      source: //172.31.1.23/Media
    nodeStageSecretRef:
      name: smb-creds-media
      namespace: kube-system

