kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-smb-media
  namespace: linkding
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-smb-media
  storageClassName: manual

