apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: seerr
  namespace: seerr
spec:
  secretName: seerr-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - seerr.cruznet.io

