apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: csi-driver-smb2
    namespace: kube-system
spec:
    interval: 30m
    chart:
        spec:
            chart: csi-driver-smb
            version: 1.20.0
            sourceRef:
                kind: HelmRepository
                name: csi-driver-smb
                namespace: kube-system
            interval: 12h
    driftDetection:
        mode: enabled
    values:
      driver:
        name: smb2.csi.k8s.io

      controller:
        name: csi-smb2-controller

      rbac:
        name: smb2

      serviceAccount:
        controller: csi-smb2-controller-sa
        node: csi-smb2-node-sa

      node:
        name: csi-smb2-node
        livenessProbe:
          healthPort: 29643

