apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prometheus-stack
resources:
  - ../../base/prometheus-stack

patches:
- target:
    kind: IngressRoute
    name: grafana
  patch: |-
    - op: replace
      path: /spec/routes/0/match
      value: Host(`grafana.staging.cruznet.io`)
- target:
    kind: Certificate
    name: grafana
  patch: |-
    - op: replace
      path: /spec/dnsNames/0
      value: grafana.staging.cruznet.io

