apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: overseerr
  namespace: overseerr
spec:
  secretName: overseerr-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - overseerr-new.cruznet.io
  - overseerr.cruznet.io

