apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: overseerr-service-account
  namespace: overseerr
  labels:
    app.kubernetes.io/name: overseerr
  annotations:
    kubernetes.io/service-account.name: overseerr

