apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: audiobookshelf
  namespace: audiobookshelf
spec:
  secretName: audiobookshelf-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - audiobookshelf.cruznet.io
  - abs.cruznet.io

