apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: audiobookshelf-service-account
  namespace: audiobookshelf
  labels:
    app.kubernetes.io/name: audiobookshelf
  annotations:
    kubernetes.io/service-account.name: audiobookshelf

