apiVersion: v1
kind: ServiceAccount
metadata:
  name: audiobookshelf
  namespace: audiobookshelf
  labels:
    app.kubernetes.io/name: audiobookshelf
secrets:
  - name: audiobookshelf-service-account

