apiVersion: v1
kind: PersistentVolume
metadata:
  name: audiobookshelf-config
spec:
  storageClassName: audiobookshelf-config
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: audiobookshelf-config
    volumeAttributes:
      dataLocality: best-effort
      numberOfReplicas: "1"
      staleReplicaTimeout: "30"
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: "5Gi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-config-claim
spec:
  storageClassName: audiobookshelf-config
  volumeName: audiobookshelf-config
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "5Gi"

