apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:ZtlKlC8dxlumJU7KuSApCd3M8hYLIUCzZTavpGxjXc1JScgif3Wfh7LIsM/ulGC94SXhd/HX/dQ=,iv:a3PMZHpKIMDkVb4sWcfsptPqLwVRVBTjkxZ/Gl4XTG8=,tag:3rvFVqYdEmjJpuy9NGMGBw==,type:str]
kind: Secret
metadata:
    name: renovate-container-env
sops:
    age:
        - recipient: age1f9ndju9c2tp8vae2lkwrenx8sk4f0zk236wlzufq8hg302gkqatsalpapg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFcG4wQnRnMXcveVdPVUIv
            VVYvZVVjaGVRTlliTll2R1BSRTN4THNMT0Q0CndjdzdIK2J4MFdXeUYzbnpMd0tu
            Y0ZkOWFtVWQybkdjZkJIYzhwSkN0Q1kKLS0tIFlFR1ZVN003SVlqQTlyQ3FhZUh1
            VXlwTGZJbGd5dTlhQTFhMHZCRTJXV28KfaZx1VqIKFY2MxXCbRgXwF23SUw2xWAy
            7OJSf1wvhej2ad5s3mt324Lqs4UJyjdDC5xkNDIFaYk01fw6t4SRPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T16:20:35Z"
    mac: ENC[AES256_GCM,data:rqozHLbVd3gnSesYm6CWehSRHzH5PUL3hT38qgkT+yzOMICxJhVkm/uQI60RtOlsDFsaU+mVBye5UOAg17PcRWCSfhujXmPsEhxZwfOmlhbStx+QOgL0jQX2VhdbxVAS7JcRWfUrswTT1OXsNA/DNe7LErPF6oJq/iZj+vVYQKE=,iv:p5rdmygft/A0V3B1nm7SNcs7CR2YYVSjv2jRTRZvqW0=,tag:Fs5+zaWARgYosYsytA7oxQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.0
