apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:OVwLNMsIvR4nW28FKBIjwg9oo6FaJLX1EVCqmjwP7JZ2hN+3c9pCERk0A8GyThAnyUb7kMBNV2w=,iv:KIEVknmjmznzEewrY/Kt4TtcRkMhPcSQLkn8qmlVNQ0=,tag:znY0SrI5idYKaEbs8Eg78g==,type:str]
kind: Secret
metadata:
    name: renovate-container-env
sops:
    age:
        - recipient: age1f9ndju9c2tp8vae2lkwrenx8sk4f0zk236wlzufq8hg302gkqatsalpapg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFcG4wQnRnMXcveVdPVUIv
            VVYvZVVjaGVRTlliTll2R1BSRTN4THNMT0Q0CndjdzdIK2J4MFdXeUYzbnpMd0tu
            Y0ZkOWFtVWQybkdjZkJIYzhwSkN0Q1kKLS0tIFlFR1ZVN003SVlqQTlyQ3FhZUh1
            VXlwTGZJbGd5dTlhQTFhMHZCRTJXV28KfaZx1VqIKFY2MxXCbRgXwF23SUw2xWAy
            7OJSf1wvhej2ad5s3mt324Lqs4UJyjdDC5xkNDIFaYk01fw6t4SRPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T16:57:32Z"
    mac: ENC[AES256_GCM,data:tSW8/HEBfwJuqXir48qzOOw1RifrAwYmIQjCGPJAon1MLsFSP7gFjIfcdNrZZOX7d9f9V4lCBaMXHzK3tAPH4U2fj5MJyDAYRQcsQyyb7sqYA/cOh9EEKMnYQpJ/53Ym2PyK7ICKKDUv7der3K8JD0UEgYngBNMgmEJ97T4wjhI=,iv:tCrRshm4uAkUZgMd2nFT41R8pzkQQmmGZ7h6IUyLdgU=,tag:R57xqpxCvTEyHbBb9dm/Cg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.0
