apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  secretName: longhorn-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - longhorn.cruznet.io

