apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: weekly-trim
  namespace: longhorn-system
spec:
  task: filesystem-trim
  cron: "0 3 * * 0"
  concurrency: 1
  groups:
    - default
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backup-daily-with-weekly-full
  namespace: longhorn-system
spec:
  task: backup
  cron: "0 2 * * *"
  retain: 14
  concurrency: 1
  groups: []
  parameters:
    full-backup-interval: "7"

