apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sonarr
  namespace: sonarr
spec:
  secretName: sonarr-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - sonarr-new.cruznet.io
  - sonarr.cruznet.io

