apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-data
spec:
  storageClassName: sonarr-data
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: sonarr-data
    volumeAttributes:
      dataLocality: best-effort
      numberOfReplicas: "1"
      staleReplicaTimeout: "30"
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: "5Gi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-claim
spec:
  storageClassName: sonarr-data
  volumeName: sonarr-data
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "5Gi"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-media-data
spec:
  storageClassName: media-data
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - vers=2.0
  csi:
    driver: smb2.csi.k8s.io
    readOnly: false
    volumeHandle: nas.cruznet.io/Media
    volumeAttributes:
      source: //nas.cruznet.io/Media
    nodeStageSecretRef:
      name: smb-creds-media
      namespace: kube-system
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: media-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: sonarr-media-data
  storageClassName: media-data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-sabnzbd-data
spec:
  storageClassName: sabnzbd-data
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: sabnzbd-data
    volumeAttributes:
      dataLocality: best-effort
      numberOfReplicas: "1"
      staleReplicaTimeout: "30"
  accessModes:
    - ReadWriteMany
  capacity:
    storage: "200Gi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-data-claim
spec:
  storageClassName: sabnzbd-data
  volumeName: sonarr-sabnzbd-data
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "200Gi"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: calibre-data
spec:
  storageClassName: calibre-data
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: calibre-data
    volumeAttributes:
      dataLocality: best-effort
      numberOfReplicas: "1"
      staleReplicaTimeout: "30"
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: "5Gi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-claim
spec:
  storageClassName: calibre-data
  volumeName: calibre-data
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "5Gi"

