apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reloader
  namespace: kube-system
spec:
  chart:
    spec:
      chart: reloader
      version: 0.0.117
      sourceRef:
        kind: HelmRepository
        name: stakater
        namespace: kube-system
  interval: 15m
  timeout: 5m
  releaseName: reloader
  values:
    reloader:
      autoReloadAll: true

