apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linkding-staging
resources:
  - ../../base/linkding

patches:
- target:
    kind: IngressRoute
    name: linkding
  patch: |-
    - op: replace
      path: /spec/routes/0/match
      value: Host(`linkding.staging.cruznet.io`)
- target:
    kind: Certificate
    name: linkding
  patch: |-
    - op: replace
      path: /spec/dnsNames/0
      value: linkding.staging.cruznet.io

