apiVersion: batch/v1
kind: CronJob
metadata:
  name: calibre-daily-backup
  namespace: calibre
spec:
  schedule: "0 3 * * *"
  timeZone: "US/Pacific"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: rsync-backup
              image: alpine:3.24@sha256:294b683cb724975bec92580e1e685676bd4b50bda910ddb8c51d4cabeaec77e6
              command: ["/bin/sh"]
              args:
                - "-c"
                - |
                  INCLUDE_DIRS="David Jen Alyssa"
                  apk add --no-cache rsync
                  for dir in $INCLUDE_DIRS; do
                    includes="$includes --include=$dir/***"
                  done
                  rsync -av --delete --no-perms --no-owner --no-group \
                    $includes --exclude='*' \
                    /calibre-library/ /nas-backup/
              volumeMounts:
                - name: calibre-lib
                  mountPath: /calibre-library
                  subPath: config
                - name: media
                  mountPath: /nas-backup
                  subPath: eBooks
          volumes:
            - name: calibre-lib
              persistentVolumeClaim:
                claimName: calibre-claim
            - name: media
              nfs:
                server: nas.cruznet.io
                path: /volume1/Media
                readOnly: false

