apiVersion: batch/v1
kind: CronJob
metadata:
  name: calibre-weekly-backup
  namespace: calibre
spec:
  schedule: "0 3 * * 0"  # Weekly at 03:00 Sunday
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: rsync-backup
              image: alpine:3.22@sha256:55ae5d250caebc548793f321534bc6a8ef1d116f334f18f4ada1b2daad3251b2
              command:
                - /bin/sh
                - -c
                - >
                  apk add --no-cache rsync &&
                  rsync -av --delete --no-perms --no-owner --no-group --include='David/***' --include='Jen/***' --include='Alyssa/***' --exclude='*' /calibre-library/ /nas-backup/
              volumeMounts:
                - name: calibre-lib
                  mountPath: /calibre-library
                  subPath: config
                - name: media
                  mountPath: /nas-backup
                  subPath: eBooks
          volumes:
            - name: calibre-lib
              persistentVolumeClaim:
                claimName: calibre-claim
            - name: media
              nfs:
                server: nas.cruznet.io
                path: /volume1/Media
                readOnly: false

