apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
spec:
  secretName: uptime-kuma-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - monitoring.cruznet.io

