apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: uptime-kuma-service-account
  namespace: uptime-kuma
  labels:
    app.kubernetes.io/name: uptime-kuma
  annotations:
    kubernetes.io/service-account.name: uptime-kuma

