apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd
  labels:
    app.kubernetes.io/name: sabnzbd
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sabnzbd
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sabnzbd
    spec:
      serviceAccountName: sabnzbd
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      securityContext:
        fsGroup: 33
        runAsUser: 33
        runAsGroup: 33
      containers:
      - name: sabnzbd
        image: lscr.io/linuxserver/sabnzbd:latest
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: PUID
          value: "33"
        - name: PGID
          value: "33"
        - name: TZ
          value: "America/Los_Angeles"
        volumeMounts:
        - name: config
          mountPath: /config
          subPath: config
        - name: data
          mountPath: /downloads
          subPath: downloads
        - name: data
          mountPath: /watch
          subPath: downloads/watch
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: sabnzbd-config-claim
      - name: data
        persistentVolumeClaim:
          claimName: sabnzbd-data-claim

