apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: sabnzbd-service-account
  namespace: sabnzbd
  labels:
    app.kubernetes.io/name: sabnzbd
  annotations:
    kubernetes.io/service-account.name: sabnzbd

