apiVersion: v1
kind: PersistentVolume
metadata:
  name: sabnzbd-config
spec:
  storageClassName: sabnzbd-config
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: sabnzbd-config
    volumeAttributes:
      dataLocality: best-effort
      numberOfReplicas: "1"
      staleReplicaTimeout: "30"
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: "5Gi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-config-claim
spec:
  storageClassName: sabnzbd-config
  volumeName: sabnzbd-config
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "5Gi"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sabnzbd-data
spec:
  storageClassName: sabnzbd-data
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: sabnzbd-data
    volumeAttributes:
      dataLocality: best-effort
      numberOfReplicas: "1"
      staleReplicaTimeout: "30"
  accessModes:
    - ReadWriteMany
  capacity:
    storage: "200Gi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-data-claim
spec:
  storageClassName: sabnzbd-data
  volumeName: sabnzbd-data
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "200Gi"

