apiVersion: v1
kind: PersistentVolume
metadata:
  name: sabnzbd-data
spec:
  storageClassName: sabnzbd-data
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: sabnzbd-data
    volumeAttributes:
      dataLocality: best-effort
      numberOfReplicas: "1"
      staleReplicaTimeout: "30"
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: "100Gi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-claim
spec:
  storageClassName: sabnzbd-data
  volumeName: sabnzbd-data
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "100Gi"

