apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: radarr
  namespace: radarr
spec:
  secretName: radarr-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - radarr-new.cruznet.io
  - radarr.cruznet.io

