apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: radarr-service-account
  namespace: radarr
  labels:
    app.kubernetes.io/name: radarr
  annotations:
    kubernetes.io/service-account.name: radarr

