apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-data
spec:
  storageClassName: radarr-data
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: radarr-data
    volumeAttributes:
      dataLocality: best-effort
      numberOfReplicas: "1"
      staleReplicaTimeout: "30"
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: "5Gi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-claim
  labels:
    recurring-job.longhorn.io/source: "enabled"
    recurring-job.longhorn.io/backup-daily-with-weekly-full: "enabled"
spec:
  storageClassName: radarr-data
  volumeName: radarr-data
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "5Gi"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-sabnzbd-data
spec:
  storageClassName: sabnzbd-data
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: sabnzbd-data
    volumeAttributes:
      dataLocality: best-effort
      numberOfReplicas: "1"
      staleReplicaTimeout: "30"
  accessModes:
    - ReadWriteMany
  capacity:
    storage: "200Gi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-data-claim
spec:
  storageClassName: sabnzbd-data
  volumeName: radarr-sabnzbd-data
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "200Gi"

