apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: seerr
  namespace: seerr
spec:
  interval: 30m
  chart:
    spec:
      chart: seerr
      version: 3.0.1
      sourceRef:
        kind: HelmRepository
        name: seerr
        namespace: seerr
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  valuesFrom:
  - kind: ConfigMap
    name: seerr-values

