apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: seerr-service-account
  namespace: seerr
  labels:
    app.kubernetes.io/name: seerr
  annotations:
    kubernetes.io/service-account.name: seerr

