apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homepage
  namespace: homepage
spec:
  secretName: homepage-cert
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
  - homepage.cruznet.io

