apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-config
  namespace: homepage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: homepage-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        kubernetes.yaml: |
          mode: cluster
        settings.yaml: |
          title: cruznet.io
          headerStyle: boxed

          background:
            image: https://images.unsplash.com/photo-1610296669228-602fa827fc1f\?q\=80\&w\=2875\&auto\=format\&fit\=crop\&ixlib\=rb-4.0.3\&ixid\=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
            # blur: sm
            brightness: 100
            opacity: 10

          providers:
            openweathermap: openweathermapapikey
            weatherapi: weatherapiapikey

          layout:
            Arr Stack:
              icon: mdi-multimedia-#FFFFFF
            Infrastructure:
              icon: mdi-network-#FFFFFF
            Monitoring:
              icon: mdi-list-status-#FFFFFF
            Infrastructure and Data:
              icon: mdi-server-#FFFFFF
            Management:
              icon: mdi-auto-fix-#FFFFFF
            Automation:
              icon: mdi-cog-play-#FFFFFF
            IoT and Smarthome:
              icon: mdi-home-#FFFFFF
            Security and Identity:
              icon: mdi-shield-lock-#FFFFFF
        custom.css: ""
        custom.js: ""
        bookmarks.yaml: |
          # For configuration options and examples, please see:
          # https://gethomepage.dev/configs/bookmarks

          - Media Content Sources:
              - IMDB:
                  - abbr: IM
                    href: https://imdb.com
              - IMDB Watchlist:
                  - abbr: IM
                    href: https://imdb.com/user/ur63521445/watchlist
              - Reelgood:
                  - abbr: RG
                    href: https://reelgood.com
              - DVDs Release Dates:
                  - abbr: DR
                    href: https://dvdsreleasedates.com

          - Developer:
              - Github:
                  - abbr: GH
                    href: https://github.com

          - Social:
              - Reddit:
                  - abbr: RE
                    href: https://reddit.com

          - Entertainment:
              - YouTube:
                  - abbr: YT
                    href: https://youtube.com
        services.yaml: |
          - Monitoring:
              - UptimeRobot:
                  href: https://dashboard.uptimerobot.com/monitors
                  icon: uptime-kuma.png
                  description: External monitoring
                  siteMonitor: https://dashboard.uptimerobot.com
                  widget:
                    type: uptimerobot
                    url: https://api.uptimerobot.com
                    key: {{ .uptimerobot_apikey }}
                    fields: ["status", "uptime", "lastDown", "downDuration"]
              - Uptime Kuma:
                  href: https://monitoring.cruznet.io
                  icon: uptime-kuma.png
                  description: Internal monitoring
                  siteMonitor: https://monitoring.cruznet.io
                  widget:
                    type: uptimekuma
                    url: https://monitoring.cruznet.io
                    slug: cruznet
          - Infrastructure:
              - Firewall:
                  href: https://cruzwall.cruznet.io
                  icon: pfsense.png
                  description: pfSense firewall
                  siteMonitor: https://cruzwall.cruznet.io
                  widget:
                    type: pfsense
                    url: https://cruzwall.cruznet.io
                    headers:
                      X-API-Key: {{ .pfsense_apikey }}
                    wan: igc3
                    version: 2
                    fields: ["load", "memory", "wanStatus", "wanIP"]
              - Switch:
                  href: http://172.31.1.3
                  icon: cisco.png
                  description: Cisco switch
                  ping: 172.31.1.3
              - Synology:
                  href: https://nas.cruznet.io:5001
                  icon: synology.png
                  description: Network attached storage
                  siteMonitor: https://nas.cruznet.io:5001
                  widget:
                    type: diskstation
                    url: https://nas.cruznet.io:5001
                    username: {{ .synology_username }}
                    password: {{ .synology_password }}
              # - UniFi:
              #     href: https://unifi.cruznet.io
              #     icon: unifi.png
              #     description: Wireless manager
              #     siteMonitor: https://unifi:8443
              #     widget:
              #       type: unifi
              #       url: https://unifi:8443
              #       username: {{ .unifi_username }}
              #       password: {{ .unifi_password }}
              - Traefik:
                  href: https://traefik-new.cruznet.io
                  icon: traefik.png
                  description: Reverse proxy
                  siteMonitor: https://traefik-new.wsgc.com
                  widget:
                    type: traefik
                    url: https://traefik-new.cruznet.io
          - Arr Stack:
              - Plex:
                  href: https://plex.cruznet.io:32400
                  icon: plex.png
                  description: Media server
                  siteMonitor: https://plex.cruznet.io:32400
                  widget:
                    type: plex
                    url: https://plex.cruznet.io:32400
                    key: {{ .plex_apikey }}
              # - Tautulli:
              #     href: https://tautulli.cruznet.io
              #     icon: tautulli.png
              #     description: Monitors Plex Media Server activity and tracks various statistics
              #     siteMonitor: http://tautulli:8181
              #     widget:
              #       type: tautulli
              #       url: http://tautulli:8181
              #       key: {{ .tautulli_apikey }}
              #       enableUser: true
              #       showEpisodeNumber: true
              #       expandOneStreamToTwoRows: true
              - Overseerr:
                  href: https://overseerr.cruznet.io
                  icon: overseerr.png
                  description: A tool that helps you find and request media for your Plex server
                  siteMonitor: https://overseerr.cruznet.io
                  widget:
                    type: overseerr
                    url: https://overseerr.cruznet.io
                    key: {{ .overseerr_apikey }}
              # - Sonarr:
              #     href: https://sonarr.cruznet.io
              #     icon: sonarr.png
              #     description: TV show collection manager
              #     siteMonitor: http://sonarr:8989
              #     widget:
              #       type: sonarr
              #       url: http://sonarr:8989
              #       key: {{ .sonarr_apikey }}
              #       enableQueue: true
              # - Radarr:
              #     href: https://radarr.cruznet.io
              #     icon: radarr.png
              #     description: Movie collection manager
              #     siteMonitor: http://radarr:7878
              #     widget:
              #       type: radarr
              #       url: http://radarr:7878
              #       key: {{ .radarr_apikey }}
              #       enableQueue: true
              # - Calibre:
              #     href: https://calibre.cruznet.io
              #     icon: calibre.png
              #     description: E-book collection manager
              #     siteMonitor: http://calibre:8080
              # - Readarr:
              #     href: https://readarr.cruznet.io
              #     icon: readarr.png
              #     description: E-book collection manager
              #     siteMonitor: http://readarr:8787
              #     widget:
              #       type: readarr
              #       url: http://readarr:8787
              #       key: {{ .readarr_apikey }}
              # - Listenarr:
              #     href: https://listenarr.cruznet.io
              #     icon: readarr.png
              #     description: Audiobook collection manager
              #     siteMonitor: http://listenarr:8787
              #     widget:
              #       type: readarr
              #       url: http://listenarr:8787
              #       key: {{ .listenarr_apikey }}
              # - Prowlarr:
              #     href: https://prowlarr.cruznet.io
              #     icon: prowlarr.png
              #     description: Usenet indexer manager
              #     siteMonitor: http://prowlarr:9696
              #     widget:
              #       type: prowlarr
              #       url: http://prowlarr:9696
              #       key: {{ .prowlarr_apikey }}
              # - SABnzbd:
              #     href: https://sabnzbd.cruznet.io
              #     icon: sabnzbd.png
              #     description: Usenet download client
              #     siteMonitor: http://sabnzbd:8080
              #     widget:
              #       type: sabnzbd
              #       url: http://sabnzbd:8080
              #       key: {{ .sabnzbd_apikey }}
              # - qBittorrent:
              #     href: https://qbittorrent.cruznet.io
              #     icon: qbittorrent.png
              #     description: Bittorrent download client
              #     siteMonitor: https://qbittorrent.cruznet.io
              #     widget:
              #       type: qbittorrent
              #       url: https://qbittorrent.cruznet.io
              #       username: {{ .qbittorrent_username }}
              #       password: {{ .qbittorrent_password }}
              #       enableLeechProgress: true
        widgets.yaml: |
          - kubernetes:
              cluster:
                show: true
                cpu: true
                memory: true
                showLabel: true
                label: "cluster"
              nodes:
                show: false
                cpu: true
                memory: true
                showLabel: true
          - resources:
              backend: resources
              expanded: true
              cpu: true
              memory: true
              network: default
              disk: /
          - search:
              provider: duckduckgo
              target: _blank
        docker.yaml: ""
  data:
    - secretKey: qbittorrent_username
      remoteRef:
        key: qbittorrent
        property: username
    - secretKey: qbittorrent_password
      remoteRef:
        key: qbittorrent
        property: password
    - secretKey: pfsense_apikey
      remoteRef:
        key: pfsense
        property: apikey
    - secretKey: synology_username
      remoteRef:
        key: synology
        property: username
    - secretKey: synology_password
      remoteRef:
        key: synology
        property: password
    - secretKey: unifi_username
      remoteRef:
        key: unifi
        property: username
    - secretKey: unifi_password
      remoteRef:
        key: unifi
        property: password
    - secretKey: plex_apikey
      remoteRef:
        key: plex
        property: apikey
    - secretKey: tautulli_apikey
      remoteRef:
        key: tautulli
        property: apikey
    - secretKey: overseerr_apikey
      remoteRef:
        key: overseerr
        property: apikey
    - secretKey: sonarr_apikey
      remoteRef:
        key: sonarr
        property: apikey
    - secretKey: radarr_apikey
      remoteRef:
        key: radarr
        property: apikey
    - secretKey: readarr_apikey
      remoteRef:
        key: readarr
        property: apikey
    - secretKey: listenarr_apikey
      remoteRef:
        key: listenarr
        property: apikey
    - secretKey: prowlarr_apikey
      remoteRef:
        key: prowlarr
        property: apikey
    - secretKey: sabnzbd_apikey
      remoteRef:
        key: sabnzbd
        property: apikey
    - secretKey: uptimerobot_apikey
      remoteRef:
        key: uptimerobot
        property: apikey

