apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homepage
resources:
  - certificate.yaml
  - cluster-role.yaml
  - config-secret.yaml
  - deployment.yaml
  - ingress.yaml
  - namespace.yaml
  - secret.yaml
  - service-account.yaml
  - service.yaml

