apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: metrics-server
    namespace: kube-system
spec:
    interval: 30m
    chart:
        spec:
            chart: metrics-server
            version: 3.13.x
            sourceRef:
                kind: HelmRepository
                name: metrics-server
                namespace: kube-system
            interval: 12h

