apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: image-pre-puller
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: image-pre-puller
  template:
    metadata:
      labels:
        app: image-pre-puller
    spec:
      initContainers:
        - name: pull-plex
          image: lscr.io/linuxserver/plex:1.43.1@sha256:1dd281365d61fb76fd4474ba67e36ec94d2e8dbc67a8032ba10731c01701c97e
          command: ["sh", "-c", "echo pulled Plex"]
        - name: pull-seerr
          image: ghcr.io/seerr-team/seerr:v3.1.0@sha256:b35ba0461c4a1033d117ac1e5968fd4cbe777899e4cbfbdeaf3d10a42a0eb7e9
          command: ["sh", "-c", "echo pulled Seerr"]
        - name: pull-audiobookshelf
          image: ghcr.io/advplyr/audiobookshelf:2.33.1@sha256:a4a5841bba093d81e5f4ad1eaedb4da3fda6dbb2528c552349da50ad1f7ae708
          command: ["sh", "-c", "echo pulled Audiobookshelf"]
        - name: pull-uptime-kuma
          image: louislam/uptime-kuma:2.2.1@sha256:7337368a77873f159435de9ef09567f68c31285ed5f951dec36256c4b267ee44
          command: ["sh", "-c", "echo pulled Uptime Kuma"]
      containers:
        - name: pause
          image: registry.k8s.io/pause:3.10@sha256:ee6521f290b2168b6e0935a181d4cff9be1ac3f505666ef0e3c98fae8199917a
          resources:
            requests:
              cpu: 1m
              memory: 4Mi

