apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: image-pre-puller
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: image-pre-puller
  template:
    metadata:
      labels:
        app: image-pre-puller
    spec:
      initContainers:
        - name: pull-plex
          image: lscr.io/linuxserver/plex:1.43.2@sha256:5a2dca89f4b53222ba2565ffa9ede3f320f37a69ac4b7fd475b492f772c5523b
          command: ["sh", "-c", "echo pulled Plex"]
        - name: pull-seerr
          image: ghcr.io/seerr-team/seerr:v3.3.0@sha256:c92d2dc117f62185e7bcb88cd56efd374ea79210eaf433275449e8d5988eb5a8
          command: ["sh", "-c", "echo pulled Seerr"]
        - name: pull-audiobookshelf
          image: ghcr.io/advplyr/audiobookshelf:2.35.1@sha256:1eef6716183c52abafe5405e7d6be8390248ecd59c7488c44af871757ac8fc4d
          command: ["sh", "-c", "echo pulled Audiobookshelf"]
        - name: pull-uptime-kuma
          image: louislam/uptime-kuma:2.4.0@sha256:91e963bfda569ba115206e843febb446f473ab525add4e08b2b9e3beffa16985
          command: ["sh", "-c", "echo pulled Uptime Kuma"]
      containers:
        - name: pause
          image: registry.k8s.io/pause:3.10@sha256:ee6521f290b2168b6e0935a181d4cff9be1ac3f505666ef0e3c98fae8199917a
          resources:
            requests:
              cpu: 1m
              memory: 4Mi

