apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-repository.yaml
  - helm-release.yaml
  - storage.yaml

configMapGenerator:
- name: vault-values
  files:
  - values.yaml

configurations:
- kustomize-config.yaml

