global:
  namespace: vault
server:
  dataStorage:
    storageClass: vault-data
    labels:
      recurring-job.longhorn.io/source: "enabled"
      recurring-job.longhorn.io/backup-daily-with-weekly-full: "enabled"
csi:
  # Settings for the daemonSet used to run the provider.
  daemonSet:
    providersDir: "/etc/kubernetes/secrets-store-csi-providers"
