apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: unifi
  namespace: unifi
spec:
  secretName: unifi-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - unifi-new.cruznet.io
  - unifi.cruznet.io

