apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: unifi
resources:
  - namespace.yaml
  - deployment.yaml
  - storage.yaml
  - service-account.yaml
  - secret.yaml
  - service.yaml
  - ingress.yaml
  - certificate.yaml
  - ip-pool.yaml

