apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: unifi-service-account
  namespace: unifi
  labels:
    app.kubernetes.io/name: unifi
  annotations:
    kubernetes.io/service-account.name: unifi

