apiVersion: v1
kind: Service
metadata:
  name: unifi-ui
  namespace: unifi
  labels:
    app.kubernetes.io/name: unifi
  annotations:
spec:
  type: ClusterIP
  ports:
  - port: 8443
    targetPort: 8443
    protocol: TCP
    name: webui
  selector:
    app.kubernetes.io/name: unifi
---
apiVersion: v1
kind: Service
metadata:
  name: unifi
  namespace: unifi
  labels:
    app.kubernetes.io/name: unifi
  annotations:
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: communication
  - port: 3478
    targetPort: 3478
    protocol: UDP
    name: stun
  - port: 10001
    protocol: UDP
    targetPort: 10001
    name: discovery
  - port: 5514
    protocol: UDP
    targetPort: 5514
    name: syslog
  - port: 6789
    protocol: TCP
    targetPort: 6789
    name: speed-test
  - port: 1900
    protocol: UDP
    targetPort: 1900
    name: l2-discovery
  selector:
    app.kubernetes.io/name: unifi
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: unifi
  namespace: unifi
spec:
  insecureSkipVerify: true

