apiVersion: v1
kind: PersistentVolume
metadata:
  name: unifi-data
spec:
  storageClassName: unifi-data
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: unifi-data
    volumeAttributes:
      dataLocality: best-effort
      numberOfReplicas: "1"
      staleReplicaTimeout: "30"
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: "8Gi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-claim
spec:
  storageClassName: unifi-data
  volumeName: unifi-data
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "8Gi"

