apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: readarr
  namespace: readarr
spec:
  secretName: readarr-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - readarr-new.cruznet.io
  - readarr.cruznet.io

