apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium
  # - cert-manager
  # - prometheus-stack
  # - csi-driver-smb
  # - vault
  # - external-secrets
  # - longhorn

