apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
- helm-release.yaml
- helm-repository.yaml

configMapGenerator:
- name: cilium-values
  files:
  - values.yaml

configurations:
- kustomize-config.yaml

