apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: cloudflare
    namespace: cert-manager
spec:
    acme:
        email: ENC[AES256_GCM,data:9GLXe10cfTndwNRzmhda0+Um26qcdVsWSHin,iv:lji4kDRMBS/fm1a8hPJ85pKqsDnJShdDNsPv6t/KLiY=,tag:FaLG/oix8L85wsB7Js12ew==,type:str]
        server: https://acme-v02.api.letsencrypt.org/directory
        privateKeySecretRef:
            name: cloudflare-clusterissuer-account-key
        solvers:
            - dns01:
                cloudflare:
                    apiTokenSecretRef:
                        name: cloudflare
                        key: api-token
sops:
    age:
        - recipient: age1f9ndju9c2tp8vae2lkwrenx8sk4f0zk236wlzufq8hg302gkqatsalpapg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1WFB6ZkY0V0dFa3haQjVJ
            eE9zTlRuS283SnNZNjQ0OUVlbzl3amhFVkIwCklRekJ3b2E0OVlEZW5jdHl1aEFy
            MWcrQldCTEphd0dQRHVYN055eVdnL28KLS0tIDZiNVpqbFQ5Rk9iQldhclArTFY1
            anlUc1I5b1VwUFI2cnJyWXczL2ZyZzQKcLDb3wHfkUm4Jq4b/Ox3oBNgZDF1XhaY
            faFTKOGcyqF4NiU4+S098Nieuv3N+XRNRr/mY6nHpLDccKtpyc7uww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-19T01:25:44Z"
    mac: ENC[AES256_GCM,data:PgpnO++TMZOtDJAiB6F7heEyMC9PkKOiQN5yFv3ry6iFXkjPher4q7iTHiNor8HkiiFTYwBiClwZDjq0zz8Mi2X412MTd4T5jqY21j4uRmfhBD+P6/nj36z6ib9Fj5yftx/Ta7INxM1SsArrZiNYEW9x4eqgR2UKaxA8MI7Qe+o=,iv:IY5CmQJH7byz9xi0FxYGkN4cI0lKoxSk5DhlkjRTPL4=,tag:0LuUyXg88EQSfeudrpBmmA==,type:str]
    encrypted_regex: ^email$
    version: 3.10.2
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: cloudflare-staging
    namespace: cert-manager
spec:
    acme:
        email: ENC[AES256_GCM,data:cjAEfm2nLDG6ydj17QMB9Wtxak6JkNbA4xal,iv:mAYF6bJnA/NGkVwC4qEpCw2E55QMoYHp03ltNE1ys6Q=,tag:UYPCXoH/Nc6BSe2eAf1+dQ==,type:str]
        server: https://acme-staging-v02.api.letsencrypt.org/directory
        privateKeySecretRef:
            name: cloudflare-clusterissuer-account-key
        solvers:
            - dns01:
                cloudflare:
                    apiTokenSecretRef:
                        name: cloudflare
                        key: api-token
sops:
    age:
        - recipient: age1f9ndju9c2tp8vae2lkwrenx8sk4f0zk236wlzufq8hg302gkqatsalpapg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1WFB6ZkY0V0dFa3haQjVJ
            eE9zTlRuS283SnNZNjQ0OUVlbzl3amhFVkIwCklRekJ3b2E0OVlEZW5jdHl1aEFy
            MWcrQldCTEphd0dQRHVYN055eVdnL28KLS0tIDZiNVpqbFQ5Rk9iQldhclArTFY1
            anlUc1I5b1VwUFI2cnJyWXczL2ZyZzQKcLDb3wHfkUm4Jq4b/Ox3oBNgZDF1XhaY
            faFTKOGcyqF4NiU4+S098Nieuv3N+XRNRr/mY6nHpLDccKtpyc7uww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-19T01:25:44Z"
    mac: ENC[AES256_GCM,data:PgpnO++TMZOtDJAiB6F7heEyMC9PkKOiQN5yFv3ry6iFXkjPher4q7iTHiNor8HkiiFTYwBiClwZDjq0zz8Mi2X412MTd4T5jqY21j4uRmfhBD+P6/nj36z6ib9Fj5yftx/Ta7INxM1SsArrZiNYEW9x4eqgR2UKaxA8MI7Qe+o=,iv:IY5CmQJH7byz9xi0FxYGkN4cI0lKoxSk5DhlkjRTPL4=,tag:0LuUyXg88EQSfeudrpBmmA==,type:str]
    encrypted_regex: ^email$
    version: 3.10.2

