apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vault
  namespace: vault
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`vault.staging.cruznet.io`)
    kind: Rule
    services:
    - name: vault
      kind: Service
      namespace: vault
      port: 8201
  tls:
    secretName: vault-cert

