apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - ../../base/cilium

configMapGenerator:
- name: cilium-values
  behavior: replace
  files:
  - values.yaml

