apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkding
  namespace: linkding
spec:
  secretName: linkding
  issuerRef:
    name: cloudflare-staging
    kind: ClusterIssuer
  dnsNames:
  - linkding.staging.cruznet.io

