apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkding
  namespace: linkding
spec:
  secretName: linkding-cert
  issuerRef:
    name: cloudflare
    kind: ClusterIssuer
  dnsNames:
  - linkding.staging.cruznet.io

