apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkding
  namespace: linkding
spec:
  secretName: linkding-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - linkding.cruznet.io

