apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: linkding
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`linkding.staging.cruznet.io`)
    kind: Rule
    services:
    - name: linkding
      kind: Service
      namespace: linkding
      port: 9090
  tls:
    secretName: linkding-cert

