apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: linkding
  namespace: linkding
  labels:
    app.kubernetes.io/name: linkding
  annotations:
    kubernetes.io/service-account.name: linkding

