apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: calibre-web-automated-service-account
  namespace: calibre-web-automated
  labels:
    app.kubernetes.io/name: calibre-web-automated
  annotations:
    kubernetes.io/service-account.name: calibre-web-automated

