apiVersion: v1
kind: ServiceAccount
metadata:
  name: calibre-web-automated
  namespace: calibre-web-automated
  labels:
    app.kubernetes.io/name: calibre-web-automated
secrets:
  - name: calibre-web-automated-service-account

