apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: plex
resources:
- namespace.yaml
- helm-repository.yaml
- helm-release.yaml
- storage.yaml
- service-account.yaml
- secret.yaml
# - ingress.yaml
# - certificate.yaml
# - ip-pool.yaml


configMapGenerator:
- name: plex-values
  files:
  - values.yaml

configurations:
- kustomize-config.yaml

