apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rustdesk
resources:
  - namespace.yaml
  - deployment.yaml
  - storage.yaml
  - service-account.yaml
  - secret.yaml
  - service.yaml
  - ip-pool.yaml

